CREATE TABLE stories (
id INT(11) AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(255) NOT NULL,
location VARCHAR(255) NOT NULL,
story TEXT NOT NULL,
image VARCHAR(255),
user_id INT(11) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY (user_id) REFERENCES users(user_id)
);

ALTER TABLE stories
MODIFY image BLOB;

